name: Export Azure Table and Commit

on:
  schedule:
    - cron: '0 */6 * * *'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

  push:
    branches:
      - main

jobs:
  export-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'

      - name: Run Exporter
        run: |
            cd src/aka.exporter
            dotnet run $GITHUB_WORKSPACE/exports/aka-export.csv
        env:
          AKA_TABLE_CONNECTION_STRING: ${{ secrets.AKA_TABLE_CONNECTION_STRING }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./exports

      - name: Push to generated-report branch
        run: |
          mkdir temp-publish
          cp exports/aka-export.md temp-publish/README.md
          cd temp-publish
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin generated-report || true
          git checkout -B generated-report origin/generated-report || git checkout -b generated-report
          git add README.md
          git diff --quiet && echo "No changes to push." && exit 0
          git commit -m "🔄 Auto-export markdown file"
          git push origin generated-report